### ISSUE TITLE
Lecture Hall Occupation

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/2023-04-04-MPIEvolBio#4]
The following meetings have to be moved elsewhere:

### 9:00 - 10:30 BR (Wachsmuth) 
- [x] asked to move 
- [x] agreed to move to Pink Residence Meeting Room
- [x] rescheduled with Booking System

### 10:30 - 11:30 Group Meeting (Uecker)
- [x] asked to move 
- [x] agreed to move to Pink Residence Meeting Room
- [x] rescheduled with Booking System

### 14:00 - 15:00 Evoltheo Group Meeting (Traulsen)
- [x] asked to move 
- [x] agreed to move
- [x] rescheduled with Booking System

### ~9:00 - 10:00 Lab Seminar MPB (Pauline Buffard)~
We'll start at 10:00 on Wednesday

### 15:30 - 16:30 DynOSoB Group Meeting
- [x] asked to move 
- [x] agreed to move
- [x] rescheduled with Booking System

### 14:00 - 15:00 Internal Meeting (Traulsen)
- [x] asked to move 
- [x] agreed to move
- [x] rescheduled with Booking System

**Comment by CFGrote** [comment]
Hi @Nikoleta-v3, can you take care of asking people in your department if their meeting can be moved? After their approval we have to ask booking@evolbio.mpg.de to reschedule their meeting accordingly.

**Comment by Nikoleta-v3** [comment]
### 15:30 - 16:30 DynOSoB Group Meeting

The meeting is cancelled.

**Comment by Nikoleta-v3** [comment]
The room is booked 👍🏻
