### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/2023-04-04-MPIEvolBio#5]
A draft schedule is in the wiki at https://github.com/mpievolbio-scicomp/2023-04-04-MPIEvolBio/wiki/Schedule.
- [x] Fix lecturer for each lesson/episode
- [ ] While practising the episodes, update estimated times and schedule

**Comment by Nikoleta-v3** [comment]
Installation Party will be on Monday the 3rd from 10:00am to 12:00pm in the practical room ✅
